PracticaApp/PracticaApp/Models/ErrorViewModel.cs
using System;

namespace PracticaApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticaApp/PracticaApp/Models/Recepcion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PracticaApp.Models
{
    public class Recepcion
    {
        public int Id { get; set; }
        [Display(Name = "Numero de Lote")]
        public int NumLote { get; set; }
        public string Proveedor { get; set; }
        [Display(Name = "Rut de Proveedor")]
        public string RutProveedor { get; set; }
        [Display(Name = "Peso en Kg")]
        public int PesoFruta { get; set; }

        public Recepcion(int Id, int NumLote, string Proveedor, string RutProveedor, int PesoFruta)
        {
            this.Id = Id;
            this.NumLote = NumLote;
            this.Proveedor = Proveedor;
            this.RutProveedor = RutProveedor;
            this.PesoFruta = PesoFruta;
        }

        public Recepcion()
        {

        }
    }

}

PracticaApp/PracticaApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PracticaApp.Models;

namespace PracticaApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticaApp/PracticaApp/Controllers/RecepcionController.cs
using PracticaApp.Models;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PracticaApp.Controllers
{
    public class RecepcionController : Controller
    {
        public IActionResult Index()
        {
            Recepcion recepcion = new Recepcion(1, 1,"Frule","11.111.111-1",10);
            return View(recepcion);
        }
    }
}

PracticaApp/PracticaApp/Controllers/RecepcionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PracticaApp.Models;

namespace PracticaApp.Controllers
{
    public class RecepcionsController : Controller
    {
        private readonly PracticaAppContext _context;

        public RecepcionsController(PracticaAppContext context)
        {
            _context = context;
        }

        // GET: Recepcions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Recepcion.ToListAsync());
        }

        // GET: Recepcions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recepcion = await _context.Recepcion
                .SingleOrDefaultAsync(m => m.Id == id);
            if (recepcion == null)
            {
                return NotFound();
            }

            return View(recepcion);
        }

        // GET: Recepcions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Recepcions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NumLote,Proveedor,RutProveedor,PesoFruta")] Recepcion recepcion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(recepcion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(recepcion);
        }

        // GET: Recepcions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recepcion = await _context.Recepcion.SingleOrDefaultAsync(m => m.Id == id);
            if (recepcion == null)
            {
                return NotFound();
            }
            return View(recepcion);
        }

        // POST: Recepcions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NumLote,Proveedor,RutProveedor,PesoFruta")] Recepcion recepcion)
        {
            if (id != recepcion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recepcion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecepcionExists(recepcion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recepcion);
        }

        // GET: Recepcions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recepcion = await _context.Recepcion
                .SingleOrDefaultAsync(m => m.Id == id);
            if (recepcion == null)
            {
                return NotFound();
            }

            return View(recepcion);
        }

        // POST: Recepcions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recepcion = await _context.Recepcion.SingleOrDefaultAsync(m => m.Id == id);
            _context.Recepcion.Remove(recepcion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecepcionExists(int id)
        {
            return _context.Recepcion.Any(e => e.Id == id);
        }
    }
}

PracticaApp/PracticaApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

PracticaApp/PracticaApp/Views/Recepcion/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Recepcion";
}

<h2>Recepcion</h2>

<div> ID: @Model.Id , Numero de Lote: @Model.NumLote , Proveedor: @Model.Proveedor , Peso @Model.PesoFruta Kg </div>

PracticaApp/PracticaApp/Views/Recepcions/Create.cshtml
@model PracticaApp.Models.Recepcion

@{
    ViewData["Title"] = "Create";
}

<h2>Crear</h2>

<h4>Recepcion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumLote" class="control-label"></label>
                <input asp-for="NumLote" class="form-control" />
                <span asp-validation-for="NumLote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Proveedor" class="control-label"></label>
                <input asp-for="Proveedor" class="form-control" />
                <span asp-validation-for="Proveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RutProveedor" class="control-label"></label>
                <input asp-for="RutProveedor" class="form-control" />
                <span asp-validation-for="RutProveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PesoFruta" class="control-label"></label>
                <input asp-for="PesoFruta" class="form-control" />
                <span asp-validation-for="PesoFruta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a las Recepciones</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaApp/PracticaApp/Views/Recepcions/Delete.cshtml
@model PracticaApp.Models.Recepcion

@{
    ViewData["Title"] = "Delete";
}

<h2>Eliminar Recepcion</h2>

<h3>¿Esta seguro que desea eliminar la recepcion? </h3>
<div>
    <h4>Recepcion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumLote)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumLote)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Proveedor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RutProveedor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RutProveedor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PesoFruta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PesoFruta)
        </dd>
    </dl>
    
    <form asp-action="Eliminar">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Volver a las Recepciones</a>
    </form>
</div>

PracticaApp/PracticaApp/Views/Recepcions/Details.cshtml
@model PracticaApp.Models.Recepcion

@{
    ViewData["Title"] = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Recepcion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumLote)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumLote)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Proveedor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RutProveedor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RutProveedor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PesoFruta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PesoFruta)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Volver a las Recepciones</a>
</div>

PracticaApp/PracticaApp/Views/Recepcions/Edit.cshtml
@model PracticaApp.Models.Recepcion

@{
    ViewData["Title"] = "Edit";
}

<h2>Editar</h2>

<h4>Recepcion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NumLote" class="control-label"></label>
                <input asp-for="NumLote" class="form-control" />
                <span asp-validation-for="NumLote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Proveedor" class="control-label"></label>
                <input asp-for="Proveedor" class="form-control" />
                <span asp-validation-for="Proveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RutProveedor" class="control-label"></label>
                <input asp-for="RutProveedor" class="form-control" />
                <span asp-validation-for="RutProveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PesoFruta" class="control-label"></label>
                <input asp-for="PesoFruta" class="form-control" />
                <span asp-validation-for="PesoFruta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a las Recepciones</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaApp/PracticaApp/Views/Recepcions/Index.cshtml
@model IEnumerable<PracticaApp.Models.Recepcion>

@{
    ViewData["Title"] = "Recepciones";
}

<h2>Recepciones</h2>

<p>
    <button>
        <a asp-action="Create">Agregar Recepcion</a>
    </button>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NumLote)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Proveedor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RutProveedor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PesoFruta)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumLote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Proveedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RutProveedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PesoFruta)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

PracticaApp/PracticaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frio Bueno App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Frio Bueno App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Recepcions" asp-action="">Recepciones</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - PracticaApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>